### ISSUE TITLE
Fix ownership

### ISSUE THREAD

**Issue by ProgramFan** [asciidoctor/asciidoctor-bibtex#12]
@mojavelinux, I transfered this extension to asciidoctor.org. Although I can still commit directly to this repo, I can no longer change project settings. Would you please fix that (possibly by fixing the ownership)? Thanks.

**Comment by ProgramFan** [comment]
Hi, @mojavelinux , would you please help fixing it? Thanks a lot.

**Comment by mojavelinux** [comment]
Yep, I'll do it asap. I'm just running behind on getting tasks done. Stay
tuned!

**Comment by mojavelinux** [comment]
All done. I've added to to a new team, made you the team maintainer, and gave that team admin permissions.

(This is a typical step after transferring a repository. GitHub does not currently offer a way to assign admin permissions at the time the repository is transferred. It's always an extra step).

**Comment by ProgramFan** [comment]
Thanks, @mojavelinux
