### ISSUE TITLE
intollerant to not finding a citation

### ISSUE THREAD

**Issue by shahryareiv** [asciidoctor/asciidoctor-bibtex#18]
If a citation is unknown then this message is thrown and the progress stops:
"

> Unknown reference: _cite-key_
> Failed to render  _cite-key_: can't dup NilClass

"
I think it might be better to just throw a warning. In bibtex, by default, a '?' is placed in the location . When asciidoctor-bibtex works in a chain with other tools it can get hindering. Probably the best might be to add an option to stop or not to stop on errors.

**Comment by shahryareiv** [comment]
I guess I made a mistake and it does not stop because of an unknown citation. So I close the issue.

**Comment by ProgramFan** [comment]
Yes, asciidoctor-bibtex only throws an warning and still generates the citation with the provided key. This can eventually be useful if one first add citations and then complete the bibtex file.
