### ISSUE TITLE
Unicode is not the default language (LANG=en_US.UTF-8)

### ISSUE THREAD

**Issue by shahryareiv** [asciidoctor/asciidoctor-bibtex#19]
This has been a problem with asciidoc-bib also, if there are citation with non US-ASCII letters it nags about `invalid byte sequence in US-ASCII (ArgumentError)`. One can avoid this by doing like `export LANG=en_US.UTF-8  && asciidoc-bibtex ...` but it might be better to switch to UTF-8 inside the code.

**Comment by ProgramFan** [comment]
Thanks for reporting. I will look into it when I find time. It might be a bug within bibtex-ruby.

**Comment by ProgramFan** [comment]
Would you provide details of the problem? I don't quite understand your case and can not reproduce it by using CJK chars in either citation or bibtex file.

**Comment by ProgramFan** [comment]
It seems you are using adoc to adoc mode instead of the extension mode. Can you provide some information on why using asciidoctor-bibtex as a asciidoctor extension does not fit your needs? If really necessary, I can add them back in the master.

**Comment by shahryareiv** [comment]
There are three reasons:

First the citations in side-notes, figure captions and quotes attributes are not being translated by asciidoctor-bibtex (at least at the moment). I have already these features in my writings and cannot avoid them.

The second reason is that sometimes we need an asciidoc file independently without any conversion. For example when one sends a file to an editor or a reviewer, or when one saves the file for future (freeze the text). In these cases it is not convenient to attach a bib file (which might change during time) alongside the asciidoc file. The asciidoc file needs to be final and independent as much as possible (except images). The current asciidoctor does not allow asciidoctor to asciidoctor conversion so asciidoctor-bibtex cannot generate a resolved and independent asciidoc file (I guess I should open an issue for this).

The third reason is that if one need to preprocess the asciidoc file before converting to html, or docbook then sometimes the citation things are better to be solved before preprocessing. For example if one needs to convert bibliopgrahy into footnotes or sidenotes (Tufte style) then a resolved version of the asciidoc is needed to do these stuffs.

**Comment by ProgramFan** [comment]
The asciidoc-to-asciidoc feature is removed.
