### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by getreu** [asciidoctor/asciidoctor-bibtex#21]
```
# gem install asciidoctor-bibtex
Building native extensions.  This could take a while...
ERROR:  Error installing asciidoctor-bibtex:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/unicode-0.4.4.2/ext/unicode
/usr/bin/ruby2.3 -r ./siteconf20170130-4217-o7hums.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/unicode-0.4.4.2 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/unicode-0.4.4.2/gem_make.out

```

**Comment by ProgramFan** [comment]
Hi, as the error message shows, the **unicode-0.4.4.2** gem failed to build. Asciidoctor-bibtex does not contain native extensions itself.

It seems that you have not installed the ruby header correctly. `dnf install ruby-devel` will do this for you on Fedora.

**Comment by ProgramFan** [comment]
Since this is not related with asciidoctor-bibtex, I close this issue. But feel free to ask questions.

**Comment by getreu** [comment]
Thank you!
To help people using debian based distributions:  it is `apt-get install ruby-dev`
