### ISSUE TITLE
Support for biblatex

### ISSUE THREAD

**Issue by tribut** [asciidoctor/asciidoctor-bibtex#26]
Is it planned to support using `\printbibliography` instead of `\bibliography`when using `bibliography::[]`? With biblatex, using `\bibliography` outside of the preamble is a syntax error.
If you tell me how you would want it to work, I'll submit a PR for this.

**Comment by ProgramFan** [comment]
Hi, @tribut , Do you mean that you want `bibliography::[]` to translate to biblatex's `\printbibliography`? This would be a nice addition to asciidoctor-bibtex and your PR is welcome. All you have to do is to add another output type such as 'biblatex' and implement it in processor.rb.

**Comment by tribut** [comment]
Yes. Thanks, I'll do that.
