### ISSUE TITLE
[Discussion] Locator (aka page[s]) property for citations

### ISSUE THREAD

**Issue by Fiech** [asciidoctor/asciidoctor-bibtex#36]
This will be a long one, but please bare with me. I really like this plugin, because it allows me to use bibtex-functionality directly with asciidoc, but I'd like to discuss the matter of the presentation of the locator information in citations.

During my book production, I stumbled upon the problem of locator, or page(s) localization, i.e., the "p. X" and "pp. X-Y" suffix for other languages/locales, as well as the "pp. X sq." or "pp. X sqq." part behind an inline citation.

After going through the code, I found that "p." and "pp." are handled [manually after the actual citation text is retrieved](https://github.com/asciidoctor/asciidoctor-bibtex/blob/a2de161645684b6717c33eef93118dee52606e5a/lib/asciidoctor-bibtex/processor.rb#L180-L187) from the CiteProc ruby processor.

However I found that the CiteProc ruby processor actually supports a locator parameter, which then gets used to generate the "p. X" and "pp. X-Y" suffix, as seen in the last example in the Readme of https://github.com/inukshuk/citeproc-ruby. This also has the additional benefit of changing the "p." and "pp." to their respective counterparts as defined in the locale definition file of the csl-style, now that the processor gets intialized with the locale parameter.

So, I started working on way to generate this via the means of the locator-property of the render functionality, and here is what I came up with. I commented out the manual construction of the pp-part and linked the `cite.pages` content to the locator-property of the render function, as can be seen here: [Link to commit](https://github.com/Fiech/asciidoctor-bibtex/commit/5344fc269e9f18c9ccda831c9cdf5b0707e820d3). This works pretty well, as far as I can see. The decision of how to display the citation with or without locator info is left to the CiteProc processor, which can also deal with empty pages-informations. Also with the bibtex-locale, the p. and pp. get's changed according to the csl-locale-definition.

**There is however a caveat and my first questions:**
1. I - for now - got rid of any special consideration for the `citenp` macro. However I am not really sure what the actual goal of this macro is supposed to be, to be honest. I have also noticed some really strange bugs with the `citenp` macro where in certain situations manually parantheses disappeared or the first letter of the citation was not converted to a link to the bibliography entry. **So my question is: What is this macro exactly supposed to to and do we need it?**
2. For the citation style, I now left everything to the CiteProc processor and the csl-style to decide. So, for example IEEE style does not show any pages, but I think this simply is due to the style. **Would it not be better if we would stay in accordance with the style, and ask the user to define their own custom style if they wanted to deviate from the style?** (This would also answer question 1).

Additionally to the localization of the locator string (p. and pp.), I wanted a way to get the "sq." and "sqq." in the locator information. This was not possible due to the `cite`-macro only working with a format similar to `cite:[cite_key(6)]` or `cite:[cite_key(6-8)]`, but not something like `cite:[cite_key(6 sq.)]`

In LaTeX this is done rather straight forward by using something like `\cite[6\psq]{cite_key}` or `\cite[6\psqq]{cite_key}`, where `\psq` and `\psqq` default to a non-breaking space and a localized string (sq., sqq. in English, f. and ff. in German, for example). This is not controlled by the csl-locale-definition, so I chose to open up the regexp-string in [citationutils.rb](https://github.com/Fiech/asciidoctor-bibtex/commit/06399311f878e07f559f7a1cef233d371489a8f7). This however did produce bugs when using multiple citations with pages in one `cite`-macro, so I later changed it to a more specific version as seen [here](https://github.com/Fiech/asciidoctor-bibtex/commit/5a52e4a8a4c85a85d6b013e10262f057c01d813f).

This basically allows the user to write anything they like, e.g. `cite:[cite_key(6&#160;sqq.)]`. The CiteProc processor still does it's job as expected, so the citation will be something like `(Author, Year, pp. 6 sqq.)` (for the _din-1505-2_ style in this case).

Here my question is: **Are there compelling reasons to not use this less constrained version, where the user can put any string in the citation and let the CiteProc decide how to handle this?**

Looking forward to a productive discussion.

**Comment by ProgramFan** [comment]
I accept this less constrained version. Would you please make a PR for this?

**Comment by ProgramFan** [comment]
I implemented the above version. But there exist one caveat: some styles such as `chicago-author-date` does not handle locators as expected. We have to patch that.
