### ISSUE TITLE
cite: macro does not work in tables

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctor-bibtex#39]
cite: does not work in table cells- the cite:[REF1] is not processed and appears unmodified in the output.
(Note: Started a new issue based on the discussion in issue 31.)
Reponse from 0xDiddi, copied from issue 31:
"I just reproduced your error though, and can add that other inline macros (I tested links) work inside table cells, so it seems that one is on asciidoctor-bibtex.

But notable: most blocks in asciidoctor can be reproduced by annotating an open block, only pass-through and table blocks can not.
This leads me to believe that they are handled specially within asciidoctor, so there may be something going on there as well that causes this.

EDIT: I just tested my own inline macro inside a table, and (apart from the error above) it is being processed and produces output. So I conclude that tables generally process all inline macros, not just built-in ones."

**Comment by johannesjh** [comment]
Minimal example for reproducing the issue

cite-in-table.adoc:

```adoc
:bibtex-file: example.bib
:bibtex-style: apa

This minimal example demonstrates and hopefully helps resolve the problem from 
https://github.com/asciidoctor/asciidoctor-bibtex/issues/39[asciidoctor-bibtext issue #39], 
namely that citations do not work inside tables.

Citations work in the main text, as illustrated here
cite:[McKnight2002IntegrativeTypology].

* Citations work inside lists,
* as illustrated here cite:[McKnight2002IntegrativeTypology].


[cols="1,1",options="header"]
|===
| Column
| Citation
| Unfortunately, citations do not work inside tables
| cite:[McKnight2002IntegrativeTypology]
|===
```

example.bib:

```bib
@article{McKnight2002IntegrativeTypology,
	Author = {McKnight, D Harrison and Choudhury, Vivek and Kacmar, Charles},
	Journal = {Information Systems Research},
	Number = {3},
	Pages = {334--359},
	Publisher = {INFORMS},
	Title = {Developing and validating trust measures for e-commerce: An integrative typology},
	Volume = {13},
	Year = {2002}
}
```

**Comment by johannesjh** [comment]
maybe @mojavelinux can help with this issue and #31 - my experience is that Dan was super knowledgeable and helpful when I had questions regarding asciidoctor extension points.

**Comment by mojavelinux** [comment]
As of Asciidoctor 2.0, the find_by method (which the tree processor in this extension uses) now descends into tables. In this case, the context of interest is :table_cell.

The problem with footnotes seems to be a text parsing issue in the extension.

**Comment by tfmoraes** [comment]
If the cell with the citation has the `a` operator the citation will be rendered wrongly. Using the same sample:

```asciidoc
[cols="1,1"]
|===
| Unfortunately, citations do not work inside tables
a| cite:[McKnight2002IntegrativeTypology]
|===
```

It will show:

```
cite:[McKnight2002IntegrativeTypology]
```
