### ISSUE TITLE
Regression in version 0.4.0

### ISSUE THREAD

**Issue by pela9** [asciidoctor/asciidoctor-bibtex#44]
The latest version 0.4.0 of asciidoctor-bibtex fixed the crash with asciidoctor version >= 2.0, but introduces a regression failure.  The produced reference table is OK, but he inline macros "cite:[<some-key>]" are not processed in DocBook translation but left verbatim in the DocBook output.

**Comment by gavinmacaulay** [comment]
I see the same problem with html5 (and pdf) output when using 0.4.0. Reverting to 0.3.1 removes the problem.

**Comment by ProgramFan** [comment]
I will check it.

**Comment by ProgramFan** [comment]
I see. This is caused by a PR changing `text.gsub!` to `text = text.gsub`. What is the standard way to change the text in place?
