### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by ProgramFan** [asciidoctor/asciidoctor-bibtex#45]

**Comment by ProgramFan** [comment]
See comments in #38.

**Comment by mojavelinux** [comment]
I'll take care of setting up CI as soon as we have tests to run (#46 and #41). Even if we could just get a few tests working, that will be enough to enable CI. Let me know when that happens. Thanks!

**Comment by ProgramFan** [comment]
OK.

**Comment by ProgramFan** [comment]
All tests are ported and some are failing. Would you please help setting up the CI? @mojavelinux

**Comment by ProgramFan** [comment]
All tests are passed. 😄 @mojavelinux

**Comment by mojavelinux** [comment]
Great news! Yes, I will help get it set up in the upstream account. I'll let you know when it's ready.

**Comment by mojavelinux** [comment]
Have you created a .travis.yml file? I don't see one.

**Comment by mojavelinux** [comment]
CI is activated, but since there's no .travis.yml file, nothing runs.

For an example, see https://github.com/asciidoctor/kramdown-asciidoc/blob/master/.travis.yml

It's good to test on all versions of Ruby the gem claims to support.

**Comment by mojavelinux** [comment]
Tests are now run on each merge to master and PRs that derive from it.

**Comment by mojavelinux** [comment]
Now that CI is enabled, make sure the CI build is successful before releasing.

**Comment by ProgramFan** [comment]
OK.
