### ISSUE TITLE
Rename source files

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-bibtex#57]
Ruby source files should be named in lowercase. Individual words in the class name should be separated by underscores.

* Processor.rb → processor.rb
* StringUtils.rb → string_utils.rb
* CitationMacro.rb → citation_macro.rb
* ...

Also, test files should use the `_test.rb` suffix instead of prefix:

* test_Processor.rb → processor_test.rb
* test_PathUtils.rb → path_utils_test.rb

Please rename the source files accordingly.

**Comment by ProgramFan** [comment]
OK.

**Comment by mojavelinux** [comment]
:+1:
