### ISSUE TITLE
Feature request: Customizing numbering

### ISSUE THREAD

**Issue by pddzaic** [asciidoctor/asciidoctor-bibtex#59]
Is there a way to customize the inline citation as well as the reference list: 

Example:

```
The document cite:[doc-a] should be...

[bibliography]
== References
bibliography::[]
```

> The document /1/ should be...
> 
> References
> /1/ BMW; "A dummy document"; 12345; 2019-09-01

The current situation is:

> The document [1] should be...
> 
> References
> 1. BMW; "A dummy document"; 12345; 2019-09-01

**Comment by ProgramFan** [comment]
In principle, this can be done. But what is the semantics under this customization? AFIK, bibtex and latex do not use this type of citation notation, and asciidoctor-bibtex models bibtex.

**Comment by pddzaic** [comment]
In companies, especially with references, the specification is not always 100% met, so that it can happen that certain adaptations (as I have shown as an example) are desired.
