### ISSUE TITLE
Support Citation in Figure Caption

### ISSUE THREAD

**Issue by johannesjh** [asciidoctor/asciidoctor-bibtex#60]
Please support citations inside figure captions.

Background: I am using asciidoctor for scientific writing. In this context, it is quite usual for figure captions to include citations, e.g., when the figure has been taken from another, related work.

Example:

```adoc
= Example
:bibtex-file: ./example.bib
:bibtex-style: apa

Example to demonstrate an issue with asciidoctor-bibtex 
where citations do not work within figure captions 
even though they are working correctly in the main body, 
as evident in this citation cite:[mycitation].

.Example figure from cite:[mycitation].
image::./figure.jpg[]


== Bibliography

bibliography::[]

```

See attached .zip file for a fully working minimal example:
[asciidoctor-bibtex-issue.zip](https://github.com/asciidoctor/asciidoctor-bibtex/files/3610781/asciidoctor-bibtex-issue.zip)

**Comment by ProgramFan** [comment]
This shall be possible. You just have to search for block titles and do substitution on them. A PR is welcome.
