### ISSUE TITLE
asciidoctor 2.x and -bibtex to generate tex files 

### ISSUE THREAD

**Issue by rriemann** [asciidoctor/asciidoctor-bibtex#64]
Dear all,

I just do my first steps with asciidoctor.

I use rvm and ran `gem install --pre asciidoctor-latex asciidoctor-bibtex`.

This gives me with `gem list | grep ascii`:
```
asciidoctor (2.0.10, 1.5.8)
asciidoctor-bibtex (0.6.0)
asciidoctor-latex (1.5.0.17.dev)
```

Asciidoctor is installed twice, because bibtex and latex have different version requirements on asciidoctor. I did not manage to have a successful call to create a tex with the bibtex extension. Errors I have are:
```sh
$ asciidoctor-latex -r asciidoctor-bibtex sample.adoc
  asciidoctor: FAILED: 'asciidoctor-bibtex' could not be loaded
```

How can I setup bibtex to create tex files?

**Comment by ProgramFan** [comment]
It seems asciidoctor-latex is out of date and its pulls in the old asciidoctor. asciidoctor-bibtex depends on the new asciidoctor so it can not be loaded. One workaround is to modify the asciidoctor-latex Gemfile to depend on asciidoctor-2 and use asciidoctor to load both:

```
asciidoctor -r asciidoctor-bibtex -r asciidoctor-latex -b latex <doc>.asciidoc
```
