### ISSUE TITLE
CV style bibliography?

### ISSUE THREAD

**Issue by oliviercailloux** [asciidoctor/asciidoctor-bibtex#66]
Please support generating a bibliography with every entries in a given bib file, instead of just those entries that have been cited. This is useful for generating a publication list in a CV. The list could be generated with subsections per year, ideally. See https://bibbase.org/ for inspiration.

(If this is already possible, please consider this issue as a request for indicating it in the README.)

**Comment by ProgramFan** [comment]
How can this be done in latex?

**Comment by ProgramFan** [comment]
After investigating this issue, I found there exists no clear user interface for this feature. One can cite every entry in the text to generate a full bibliography, but there exists only one big macro to print the entries. Thus it is not possible to extend the grammar for sectioned bibliography.

On the other hand, asciidoctor-bibtex tries to mimic bibtex. Yet bibtex does not support the requested feature, either.

**Comment by oliviercailloux** [comment]
Well, it all depends on how close asciidoctor-bibtex wants to be to “bibtex” per se (as opposed to mimicking what can be done more generally with LaTeX plus BibTeX plus some packages). There are multiple ways to produce a CV in LaTeX, based on BibTeX plus some additional packages (that I can’t talk about specifically, having never used such things).

But, thanks for having considered my proposition!

**Comment by ProgramFan** [comment]
I am still considering this proposition. How about this inline macro?

```asciidoc
= My Publications
== 2019

- bibitem:[Laren1a]
- bibitem:[Laren1b]
```

The `bibitem:[key]` macro will simply insert the rendered bibliography item there.

**Comment by oliviercailloux** [comment]
Nice! But if I understand correctly, this requires me to list all keys in my bib file, and sort them by year manually?

I was thinking of an automated way of doing this. Something like (pardon my syntax)

```
= My Publications
autobiblio:peryear
```

which would create subtitles per year (2019, 2018, …) and under each subtitle, put all the entries corresponding to publications of that year, ordered by date of publication and then alphabetical list of authors. ([Example](https://www.lamsade.dauphine.fr/~ocailloux/#publications))

**Comment by ProgramFan** [comment]
I understand the ease of use provided by such things. However, this would require the introduction of macros for a very specific single use case, which seems too much burden to a lightweight markup language as asciidoc.

The `bibitem` inline macro provides a mechanism to insert automatically generated bibliography entries. For personal CV, one can do it manually once and update the CV only sparingly, which shall not be too much burden. One can use other script languages to generate the required list automatically.

**Comment by oliviercailloux** [comment]
Thanks for the introduction of this macro! It will be useful indeed for generating a CV.

For the record, note that my underlying longer-term intuition was that the auto-generating macro that I had in mind would then be extended to provide for various sorts of ordering (per year, per kind of publication) or filtering (pick only those entries where I am listed as an author, …). The suggestion here was simply what I personally use, but others would differ. I was suggesting to start with this (admittedly narrow) functionality because I think agile development makes complete sense here.

If considering an extended auto-generating macro as just sketched, I disagree that it would fulfill “a very specific single use case”, or I am unsure what is meant by this. Considering the number of LaTeX packages and posts in forums about generating a bibliography of one’s own articles with LaTeX, this is a much demanded feature. Furthermore, I find it hard to think of a (correct) use case of the `bibitem` macro which would not be better fulfilled with an extended auto-generating macro of the kind just discussed: authors are not supposed to reference works that have not been cited in the text, except precisely in those cases where one is generating a list of references for the sake of having a complete list of references matching some criteria (such as in the case of a CV).

True, updating the list for maintaining a CV would not be (that) hard, but it’s precisely the kind of thing that computers do wonderfully. And in case you want to generate a publication list for a whole university, for example, this will be a nightmare. True, one can use another script for producing the list of `bibitem` entries, but this will be much more hassle for the user. For the reasons highlighted above, it seems to me that asciidoctor-bibtex could include this functionality, conceptually. 

I fully understand that you’re the one coding, not me, and that you’re the one to decide whether you have desire and time for coding this! I am only arguing for the reasonableness of this functionality.

**Comment by ProgramFan** [comment]
I understand the reasonableness of the requested functionality. I am not objecting to this idea I like it. However, I suspect the functionality as described above is actually what another tool shall provide since it needs to provide a lot of options for customizations.

Given the introduction of `bibitem` macro, a natural way to handle that would be to write another tool that can select and sort items in a bibtex database and output a cv-style asciidoc document.  The tool is not hard to implement using python, if there are enough demands.

Let's wait for someone to write such a tool.
