### ISSUE TITLE
CitationProcessor searches for bibtex-file in working dir instead of document basedir

### ISSUE THREAD

**Issue by slonopotamus** [asciidoctor/asciidoctor-bibtex#67]
https://github.com/asciidoctor/asciidoctor-bibtex/blob/409b1a1a22f4c92bd808d2322f93149a2f00d744/lib/asciidoctor-bibtex/extensions.rb#L73-L75

I believe it should pass `document.basedir` instead of `.`

**Comment by ProgramFan** [comment]
I agree.
