### ISSUE TITLE
Duplication of footnotes in lists

### ISSUE THREAD

**Issue by nitrocalcite** [asciidoctor/asciidoctor-bibtex#69]
If `asciidoc-bibtex` is used to compile a file with footnotes in the lists, those footnotes are duplicated.  Duplication does not happen if `asciidoc-bibtex` is not used, even when no bibliography is present.

Here's an example file:
```
= Test File

== Heading 1
Some text with footnote footnote:[words0]

Some text with footnote footnote:[words1]

* Some list text with footnote footnote:[list0]
* Some list text with footnote footnote:[list1]
```
If compiled with `asciidoctor $file.adoc`, the footnotes show up as expected, like this:
```
1. words0
2. words1
3. list0
4. list1
```
However, if compiled with `asciidoctor -r asciidoctor-bibtex $file.adoc`, then the footnotes "list0" and "list1" will show up twice, like this:
``` 
1. list0
2. list1
3. words0
4. words1
5. list0
6. list1
```
The hyperlinks for footnotes 1 & 2 are then broken, as they aren't referenced anywhere.

If anyone know a workaround for this, please let me know!
Thanks

**Comment by ProgramFan** [comment]
I will look into this issue.
