### ISSUE TITLE
Citations not rendered properly

### ISSUE THREAD

**Issue by barche** [asciidoctor/asciidoctor-bibtex#71]
All my citations are rendered as e.g. `[4+]+)`, i.e. there are `+` characters and a `)` that shouldn't be there. Any ideas what might cause this?

**Comment by ProgramFan** [comment]
Any test case on this issue? It looks good with my documents.

**Comment by Konachan** [comment]
Just had the same issue and had the time to test some things.
This issue appears if the `compat-mode`-Attribute is present (https://asciidoctor.org/docs/migration/#compat-mode)

**Comment by barche** [comment]
Ah, thanks! I was indeed building with `-a compat-mode` for some reason. Works fine if I remove that option, so this can be closed as far as I'm concerned.
