### ISSUE TITLE
Didn't found a way to change the locale

### ISSUE THREAD

**Issue by steven-r** [asciidoctor/asciidoctor-bibtex#72]
CSL does support a couple of localizations. 

As for now I do not know how to select a different locale besides the default one (english).

Is there any chance to support this via parameter (e.g. `:bibtex-language`)?

**Comment by mojavelinux** [comment]
It would be best to build on the built-in AsciiDoc attribute "lang", unless there's a reason to differentiate between the language of the content and the language used for the bibtex references.

**Comment by steven-r** [comment]
> It would be best to build on the built-in AsciiDoc attribute "lang", unless there's a reason to differentiate between the language of the content and the language used for the bibtex references.
> 
> Keep in mind, "lang" is an informational attribute. It only affects behavior if integrations choose to honor it.

The problem with `lang` is that it is (for asciidoctor) only a two letter code (i.e. "de" for german language). On the other side, CSL locales require qualified codes (with country included, i.e. "de-DE") . Anyhow, I would even suggest to change asciidoctor to use qualified language codes. They might give more hints and differentiate between localized names (i.e. de-CH does not know about the sharp s "ß" even if it is german language).

The same "dilemma" exists in many other systems (even several LaTeX packages are doing some magic here).

**Comment by mojavelinux** [comment]
> The problem with lang is that it is (for asciidoctor) only a two letter code (i.e. "de" for german language).

Asciidoctor doesn't enforce any particular format. As I was saying, the value is provisional. Integrations can use the value how they see if. So you could type `:lang: de-DE` and that will work just fine.

If there's a place where it should only be a two letter code, we can truncate to it.

**Comment by mojavelinux** [comment]
I agree that the documentation could be more clear that the value can be the full code. And it's up to you to decide how they map to the locale attribute files we maintain at https://github.com/asciidoctor/asciidoctor/tree/master/data/locale. Using a two-letter code is not mandatory.

**Comment by steven-r** [comment]
fine... coming back to my initial question. How to use locales for asciidoc-bibtex to use localized CSL templates. Setting :lang: doesn't help here. Setting lang to "de-DE" still uses english bibitem words:
![image](https://user-images.githubusercontent.com/4533301/98033684-28f21680-1e16-11eb-924f-3abadd8ae2bf.png)

**Comment by mojavelinux** [comment]
I think the point is that it doesn't. There's no reference to lang or anything like it in this code.

**Comment by steven-r** [comment]
huh... writing international texts with asciidoctor looks like a minefield ;) 

Is there any roadmap on i18n for the asciidoctor ecosystem? It looks like there are couple of issues open.

To get more into ruby I will have a look on this one, as I do not want to write some kind of "intelligent" postprocessing logic.

**Comment by mojavelinux** [comment]
> writing international texts with asciidoctor looks like a minefield ;)

This isn't helping your case. It's only going to make the volunteers who make this project irritated and not want to help you.

This is a community run project. If you want an improvement or enhancement, then you need to make the case for the change you want (as you have done by filing this issue) and either help resolve it or be patient for someone else to come along and solve it.

**Comment by ProgramFan** [comment]
You can use the 'bibtex-locale' document attribute. Just realize that it does not appear in the readme.
