### ISSUE TITLE
Bibliography entries with links to Bibtex URLs

### ISSUE THREAD

**Issue by SimonRekers** [asciidoctor/asciidoctor-bibtex#73]
First of all I would like to appreciate the work which already has been done! It is a great an valuable library for asciidoctor.

I was wondering if it is possible to link the bibliography items to the URLs, which can be specified for each bibliography item via of Bibtex.

**Comment by ProgramFan** [comment]
Do you want to make the citation a link to the URL field of a bibliography item? Personally I prefer the current behavier where the citation is a link to the bibliography item in the reference section, which is the same as those in latex.

If you really need that behavier, you can change processor.rb for that. A PR is welcome.

**Comment by ProgramFan** [comment]
Closed as no discussions were carried out about the requirements.
