### ISSUE TITLE
Variables not passed to included document when using bibtex and toc

### ISSUE THREAD

**Issue by vonas** [asciidoctor/asciidoctor-bibtex#74]
I am including another document in my `.adoc` document. It uses the value of a variable that I defined in my parent document before including the child document. While it's properly evaluated without a table of contents, adding the `:toc:` document attribute makes AsciiDoctor act as if I hadn't defined the variable. When I keep the `:toc:` and remove `-r asciidoctor-bibtex` from my command line arguments, it works fine as well.

This repository contains a minimal example that you can clone and test right away: [vonas/asciidoctor-bibtex-issue-74](https://github.com/vonas/asciidoctor-bibtex-issue-74). It also contains my environment information in the [README](https://github.com/vonas/asciidoctor-bibtex-issue-74#debug-info).

I'd love if this can be fixed because in the current state I can't use this extension.

Cheers!

**Comment by vonas** [comment]
Update: Including the document is not necessary to reproduce this behavior: [a288822](https://github.com/vonas/asciidoctor-bibtex-issue-74/commit/a28882216ab3149961aff5ab655e9fcf45ae5e5c)

**Comment by ProgramFan** [comment]
This looks wired. I will investigate it.

**Comment by ProgramFan** [comment]
This issue is partially fixed. To be exact, if the content does not contain variables and citations at the same time, the variable substitution is correct.

**Comment by ProgramFan** [comment]
I will close this issue. Feel free to reopen it if your problem is not solved.
