### ISSUE TITLE
Feature request: div around cite:[]

### ISSUE THREAD

**Issue by pddzaic** [asciidoctor/asciidoctor-bibtex#75]
Would it be possible to wrap the link to the references into a DIV and assign a class (i.e. cite-bibtex) to it.

`... is shown in cite:[ref1] ...`

Should be in HTML as:

```
 .... is shown in <div class="cite-bibtex"><a href='#ref1'>1</a></div> ...
```

Styling with CSS would be much easier.

**Comment by ProgramFan** [comment]
Of course. In fact this feature is trivial to implement so a PR is welcome.

**Comment by mojavelinux** [comment]
span would be more appropriate as this is an inline element, not a block.

**Comment by ProgramFan** [comment]
The class is now 'citation'.

**Comment by pddzaic** [comment]
Thank you very much for the quick implementation.
