### ISSUE TITLE
bib-tex rendering in include::xx.adoc[] file fails?

### ISSUE THREAD

**Issue by kbcb** [asciidoctor/asciidoctor-bibtex#77]
Dear BibTeX-Wizards,

asciidoctor-bibtex works fine as long as I do not include a file with citenp:[] macros.

Footnote 25 is rendered nicely, the next and following do not recognize the citenp:[] macro as such ..
Footnote 26 is the first in the include(d)::file.adoc[].

````
[25] Höpfner in: Henssler/Willemsen/Kalb, Arbeitsrecht Kommentar, 9. Aufl. 2020, § 1 AÜG, Rn. 84; sowie dort per Verweis auf Lembke, BB 2012, 2497 (2499).
[26] citenp:[bag-urt-97
[27] [1], Rn. 13.
````

Using:

````
Asciidoctor PDF 1.5.3 using Asciidoctor 2.0.12 [https://asciidoctor.org]
Runtime Environment (ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
````

In the main.adoc file I typed this just after the header:

````
:bibtex-file:   ./AÜG.bib
:bibtex-format: asciidoc
:bibtex-style:  computer-und-recht.csl
:lang:          de
````

Is this a bug or am I being misled?

**Comment by ProgramFan** [comment]
The `citenp:[bag-urt-97` shall close its brakets as `citenp:[bag-urt-97]`. Is it the case?

**Comment by kbcb** [comment]
> The `citenp:[bag-urt-97` shall close its brakets as `citenp:[bag-urt-97]`. Is it the case?

Hello ProgramFan,

Certainly it is :-)

**Comment by kbcb** [comment]
The include is not the problem.
