### ISSUE TITLE
Only inserts Latex code

### ISSUE THREAD

**Issue by phylor** [asciidoctor/asciidoctor-bibtex#79]
Thank you for this project! It looks really useful.

I'm having trouble getting it to work. The problem is that in the output documents there is Latex code instead of rendered output.

This is the output generated:

![image](https://user-images.githubusercontent.com/1394828/120243272-737e2900-c267-11eb-861a-3b92f88618d3.png)

I guess it's probably obvious what I'm doing wrong?

## Test files used

`references.bib`:
```
@book{dbi,
  author={Alina Wheeler},
  title={Designing Brand Identity},
  year={2013},
  publisher={Hoboken, New Jersey}
}
```

`test.adoc`:
```
= Test Document
:bibtex-file: references.bib
:bibtex-format: bibtex

Some text cite:[dbi]

[bibliography]
== Bibliography
bibliography::[]
```

## Commands used for generation

```
asciidoctor -r asciidoctor-bibtex test.adoc
# asciidoctor-pdf shows the same behavior as `asciidoctor`
asciidoctor-pdf -r asciidoctor-bibtex test.adoc
```

Versions used:

```
$ asciidoctor --version
Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

$ gem info asciidoctor-bibtex
asciidoctor-bibtex (0.8.0)
```

**Comment by ProgramFan** [comment]
THe problem lies here:
```asciidoc
= Test Document
:bibtex-file: references.bib
:bibtex-format: bibtex
```

Remove `bibtex-format` or set it to `asciidoc` can lead you to what you want. More details can be found in the README.

**Comment by phylor** [comment]
@ProgramFan Thank you very much for the quick response! Works like a charm now.

I wrongly assumed that `bibtex-format` describes the input format of the bibliography file. That probably doesn't make any sense though :slightly_smiling_face:
