### ISSUE TITLE
Citation style APA not working?

### ISSUE THREAD

**Issue by anneloreegger** [asciidoctor/asciidoctor-bibtex#88]
I wanted to change the citation style of a project I am working on to APA, but it seems not to work.
Every time I regenerate the pdf with asciidoctor-pdf (of course including asciidoctor-bibtex) all the citations are still in IEEE.

I have the following configuration at the beginning of my asciidoc file:
```
:bibtex-file: IP5.bib
:bibtex-order: appearance
:bibtex-style: apa
```

Is there anything wrong with this configuration? Is there something more I have to add to change the citation style from IEEE to APA?

**Comment by mojavelinux** [comment]
It works fine when I try it. Can you show the top of your AsciiDoc file up until the start of the content? It's possible that `bibtex-style` is not being defined in the document header, as is required. See https://docs.asciidoctor.org/asciidoc/latest/document/header/

**Comment by anneloreegger** [comment]
Thank you for your answer. I had another look at the link you shared. I indeed had an empty line that ended the document header. It is now working for me.
