### ISSUE TITLE
Refactor processor

### ISSUE THREAD

**Issue by ProgramFan** [asciidoctor/asciidoctor-bibtex#9]
The Processor class shall focus on retriving citation, building citation output and reference outputs. Other parts such as handling arguments and include files shall be moved to specific utils. So the processor is reusable for both asciidoc and asciidoctor.

**Comment by mojavelinux** [comment]
> So the processor is reusable for both asciidoc and asciidoctor.

Honestly, I wouldn't worry about making it work with AsciiDoc Python. That project is in the past. The focus should just be on Asciidoctor and our definition of modern AsciiDoc.

**Comment by ProgramFan** [comment]
> Honestly, I wouldn't worry about making it work with AsciiDoc Python.

I Agree. I just wonder if there are users relying on the asciidoc to asciidoc transform implemented in `asciidoc-bibtex`. It takes a significant portion of code to implement the feature and it takes time to maintain it. Do you think it is OK to drop that part? @mojavelinux

**Comment by mojavelinux** [comment]
Yes, unless we hear otherwise. The idea is to take inspiration from the original project, but to set our own course to be more faithful to the AsciiDoc syntax, easier to use and understand, and easier to maintain.

**Comment by ProgramFan** [comment]
Done.
